travis:
  secure:
    BINSTAR_TOKEN: V98Kb1lmIKkcEHzcopJ5nVbAvEiOF+yhL/YwZa22grRJ+v454ry+X3IEqWYzXlJ7lR7RTWdQbNnpjTF+s5ytediBzsPpQ7zZ6R1fs3VYD6Tvue5gHQdSHuOxUx/fq8MqkzxYgGLFJNTBtnStMDsez3NU6ZeRk+oTX0s/dPrAiQI7ccRYq5n6laOiCCE0R4fEw7/tBQc8poBSYcqs3WHu4Egh2DSu2PCczbYyQ3wrWn1w79gJTZHG3QL5K7slR4Y5Nj8v0V6UzSqxoSkjb8t3J6EvZ9WMCIlRNmHfQHkLqYcdLBeTMNXZzWJNOic0DEcngYZlTMlfPWk6xl3bH7+LHT7RbwsBRnPM7cWSvpS9gFvVcfXoCS238D3afWb5VMilZ6v71LD7+Jf/iykA970lXzychjz2I4sczoZoF1232ooY+vVFfJiBCHy7/w/KjUqc8U39PZwQ29GDc/IAvi01p7VGYHUXytVJFfF691M1buqoIxSdTGtRirtxjJQUtTzoSlOGluaqJQx/+H2ybP6cFtUy3Zv0B382399zffqH7aL5/8JZrIJr/jD8ZEAVD0lcMMY+xvMZlOxiMV7bUe+UA3CPZ8aCXAyONdGtd9VAJ7B38/isGgRFRMQV2HGnp0LJiuP75YLEEAXT6cBNg+4XK6w6CelzbdZa/qk7O9cPjVk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
